version: '3.3'

services:
  nimg:
    image: engineerhub/nimg:latest
    environment:
      - NIMG_ENVIRONMENT=production
      - NIMG_PUBLIC_UPLOAD=true
      - NIMG_STORAGE_PATH=/uploads
      - NIMG_TOKEN=super-secret
      - NIMG_PORT=8080
      - NIMG_APP_NAME=nimg
    restart: always
    ports:
      - 8080:8080 # Make sure ports are exact with NIMG_PORT variable above.
    volumes:
      - /home/alcadramin:/uploads # Make sure to change "/home/alcadramin" with your storage path.
