version: '3.3'

services:
  nimg:
    container_name: nimg
    build:
      context: ../
      dockerfile: ./docker/amd64.Dockerfile
    environment:
      - NIMG_ENVIRONMENT=production
      - NIMG_PUBLIC_UPLOAD=true
      - NIMG_STORAGE_PATH=/uploads
      - NIMG_TOKEN=super-secret
      - NIMG_DEBUG=true
      - NIMG_PORT=8080
      - NIMG_APP_NAME=nimg
    restart: always
    ports:
      - 8080:8080 # Make sure ports are exact with NIMG_PORT variable below.
    volumes:
      - /home/alcadramin:/uploads # Make sure to change "/home/alcadramin" with your storage path.
